/**
 * Sheet-boundary detection from an arbitrary photo (M2-003, FR-TPL-02) —
 * finds the 4 corners of a physical sheet of paper in a teacher-supplied
 * photo of their own existing sheet. **Not** `corner-markers.ts`'s ArUco
 * fiducial detection: a custom-template source photo has no Sharlo
 * markers printed on it (it's the teacher's pre-existing sheet, not one
 * generated by this product), so this is a generic "find the paper" CV
 * problem instead, used only once, at template-creation time, per
 * `docs/ARCHITECTURE.md` §4 ("Custom templates reuse steps 1–4 in a
 * 'detect grid from a blank/sample photo' mode") and §13 (only the
 * *derived geometry* is ever persisted — the source photo itself is
 * never uploaded or stored, per FR-TPL-02/NFR-SEC-05's "process
 * client-side, keep raw images off the server" pattern already
 * established for scanning).
 *
 * **Algorithm choice is empirically justified, not the "obvious" one.**
 * Three approaches were measured in a real browser against synthetic
 * photos with known ground-truth corners (not just assumed from
 * tutorials) before writing this module:
 *
 * 1. Canny edge detection + `findContours` + `approxPolyDP` — the
 *    "classic document scanner" approach. **Measured broken** on a
 *    rotated sheet: `findContours` never saw a single closed loop around
 *    the paper (edges from a non-axis-aligned rectangle have small gaps
 *    a 3×3 dilate doesn't reliably close), so "the largest contour" was
 *    actually a small fragment — 28–55px corner error on a ~300px test
 *    image, while still reporting a plausible-looking `rows === 4`. This
 *    is exactly the silent-wrong-answer failure mode this project's
 *    verify-empirically discipline exists to catch: it would have looked
 *    fine in code review.
 * 2. Otsu global threshold (`THRESH_BINARY + THRESH_OTSU`) +
 *    `findContours` + `minAreaRect` — robust across rotation *and* pixel
 *    noise (~1.2px error, both measured), because a global brightness
 *    threshold doesn't depend on continuous edge gradients the way Canny
 *    does. But `minAreaRect` always fits a *rectangle*, so on a genuine
 *    perspective-distorted photo (a real phone photo of a sheet is
 *    foreshortened, not just rotated — realistic case measured as a
 *    trapezoid) it forced a rectangular fit onto a trapezoidal true
 *    shape: **~40px error**.
 * 3. **Chosen: Otsu threshold + `findContours` + `approxPolyDP`.**
 *    Combines Otsu's rotation/noise robustness with `approxPolyDP`'s
 *    ability to hug a true non-rectangular quadrilateral — measured
 *    ~2.2px error on the same perspective-trapezoid case that broke
 *    `minAreaRect`. `minAreaRect` is kept only as a fallback for the
 *    (real, expected) case where `approxPolyDP` doesn't resolve to
 *    exactly 4 points on a messier real photo — always available,
 *    always exactly 4 corners, worse shape fidelity than a clean
 *    `approxPolyDP` result but strictly better than returning nothing.
 *
 * All three findings are from `/tmp` scratchpad probes (not committed —
 * see `docs/reports/SHARLO-M2-003.md`), following the exact same
 * real-in-browser-introspection methodology `corner-markers.ts` and
 * `lib/templates/aruco-marker-patterns.ts` already established on this
 * repo: never trust a text search or an assumed signature/behavior for
 * an OpenCV.js API, always load it in a real browser and check.
 *
 * **This is deliberately approximate, not a confident final answer** —
 * matching `docs/ARCHITECTURE.md` §4's own framing ("a fundamentally
 * harder, less-constrained problem than scoring a known template... we
 * don't promise unattended accuracy there") and `FR-TPL-02`'s acceptance
 * criteria, which *requires* a manual corner-drag review step precisely
 * because this can be wrong. `detectSheetBoundary` never invents a
 * result it has low confidence in: it returns `null` (not a tiny/
 * garbage quadrilateral) when no sufficiently large contour is found,
 * so the caller falls back to a full-frame default the user adjusts by
 * hand, the same "flag, don't guess" principle `corner-markers.ts` and
 * `bubble-fill.ts` already apply at their own layers.
 *
 * Otsu thresholding assumes the sheet is meaningfully lighter than its
 * background (a real, if usually true, assumption — the capture UI
 * should guide "place the sheet on a plain, contrasting surface"). When
 * that assumption doesn't hold, detection degrades gracefully to `null`
 * or a poor-quality guess — never silently corrupting a template's
 * geometry, since the review step is mandatory regardless.
 */

import type { CvMat, Point } from '../scanning/corner-markers';
import type { OpenCvRuntime } from '../scanning/opencv-loader';

interface CvContourVector {
  size: () => number;
  get: (i: number) => CvMat;
  delete: () => void;
}

interface CvRotatedRect {
  center: Point;
  size: { width: number; height: number };
  /** Degrees. Reconstructed into corners manually below — this build's `minAreaRect` result has no `.points()` method, confirmed via real introspection, not assumed. */
  angle: number;
}

export interface SheetBoundaryCv extends OpenCvRuntime {
  cvtColor: (src: CvMat, dst: CvMat, code: number) => void;
  minMaxLoc: (src: CvMat) => { minVal: number; maxVal: number };
  GaussianBlur: (src: CvMat, dst: CvMat, ksize: unknown, sigmaX: number) => void;
  threshold: (src: CvMat, dst: CvMat, thresh: number, maxval: number, type: number) => void;
  findContours: (
    image: CvMat,
    contours: CvContourVector,
    hierarchy: CvMat,
    mode: number,
    method: number,
  ) => void;
  contourArea: (contour: CvMat) => number;
  arcLength: (curve: CvMat, closed: boolean) => number;
  approxPolyDP: (curve: CvMat, approxCurve: CvMat, epsilon: number, closed: boolean) => void;
  minAreaRect: (points: CvMat) => CvRotatedRect;
  Size: new (width: number, height: number) => unknown;
  Mat: new () => CvMat & { rows: number; data32S: Int32Array };
  MatVector: new () => CvContourVector;
  COLOR_RGBA2GRAY: number;
  THRESH_BINARY: number;
  THRESH_OTSU: number;
  RETR_EXTERNAL: number;
  CHAIN_APPROX_SIMPLE: number;
}

export interface DetectedSheetBoundary {
  corners: { topLeft: Point; topRight: Point; bottomRight: Point; bottomLeft: Point };
  /** Surfaced for tests/debugging only — never shown to the user, who sees the same draggable-corners review UI regardless. */
  method: 'polygon' | 'bounding-rectangle';
}

/**
 * The largest contour must cover at least this fraction of the frame to
 * be trusted as "the sheet," not a stray smaller shape (a shadow, a
 * pen, a hand) — tunable, not a hardcoded magic number, matching
 * `docs/ARCHITECTURE.md` §4 point 5's convention for detection
 * thresholds. 15% is deliberately permissive (a photo doesn't need the
 * sheet framed tightly) while still ruling out obviously-wrong small
 * contours.
 */
export const MIN_SHEET_AREA_FRACTION = 0.15;

/**
 * A grayscale image whose brightest and darkest pixels differ by less
 * than this (out of 255) is treated as having no real sheet-vs-background
 * contrast to segment — found empirically, not assumed: a perfectly
 * uniform test image (no sheet drawn at all) measured a 0-value range
 * and Otsu still mechanically produced *some* threshold, which put the
 * *entire* image on the foreground side — `findContours` then found one
 * "contour" (the canvas's own outline), which passed every downstream
 * check (large enough, resolves to exactly 4 points via `approxPolyDP`)
 * and would have been confidently reported as "the sheet." A real sheet
 * photo measured a range of 178 in the same test, comfortably above
 * this threshold — so this catches the genuinely-featureless case
 * without rejecting real low-contrast-but-real photos.
 */
const MIN_CONTRAST_RANGE = 20;

const APPROX_EPSILON_RATIO = 0.02; // fraction of the contour's perimeter — the standard approxPolyDP starting point, empirically confirmed to resolve clean synthetic rectangles/trapezoids to exactly 4 points

/**
 * Orders 4 arbitrary (unordered, arbitrary-winding) points into
 * topLeft/topRight/bottomRight/bottomLeft, via the standard "sum and
 * difference of coordinates" trick: the top-left point has the smallest
 * x+y, the bottom-right the largest; the top-right has the largest x−y,
 * the bottom-left the smallest. Pure geometry, no OpenCV involved, so
 * it's directly unit-testable — and correct for any quadrilateral
 * that's rotated less than 45° from upright, a safe assumption for a
 * teacher photographing a sheet held/placed roughly the right way up.
 */
export function orderQuadrilateralCorners(points: readonly Point[]): {
  topLeft: Point;
  topRight: Point;
  bottomRight: Point;
  bottomLeft: Point;
} {
  if (points.length !== 4) {
    throw new Error(`orderQuadrilateralCorners requires exactly 4 points, got ${points.length}`);
  }
  const bySum = [...points].sort((a, b) => a.x + a.y - (b.x + b.y));
  const byDiff = [...points].sort((a, b) => a.x - a.y - (b.x - b.y));
  return {
    topLeft: bySum[0]!,
    bottomRight: bySum[3]!,
    topRight: byDiff[3]!,
    bottomLeft: byDiff[0]!,
  };
}

function matToPoints(mat: { rows: number; data32S: Int32Array }): Point[] {
  const points: Point[] = [];
  for (let i = 0; i < mat.rows; i++) {
    points.push({ x: mat.data32S[i * 2]!, y: mat.data32S[i * 2 + 1]! });
  }
  return points;
}

function rotatedRectToPoints(rect: CvRotatedRect): Point[] {
  const { center, size, angle } = rect;
  const rad = (angle * Math.PI) / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  const hw = size.width / 2;
  const hh = size.height / 2;
  const local: Point[] = [
    { x: -hw, y: -hh },
    { x: hw, y: -hh },
    { x: hw, y: hh },
    { x: -hw, y: hh },
  ];
  return local.map(({ x, y }) => ({
    x: center.x + x * cos - y * sin,
    y: center.y + x * sin + y * cos,
  }));
}

/**
 * Finds the 4 corners of the largest plausible sheet-shaped contour in
 * `image`. Returns `null` — never a low-confidence guess — when the
 * image has no real sheet-vs-background contrast to segment
 * (`MIN_CONTRAST_RANGE`) or nothing large enough is found afterward
 * (`MIN_SHEET_AREA_FRACTION`). See the file-level doc comment for the
 * algorithm and why it was chosen empirically over two other measured
 * alternatives.
 */
export function detectSheetBoundary(
  cv: SheetBoundaryCv,
  image: CvMat & { rows: number; cols: number },
): DetectedSheetBoundary | null {
  const gray = new cv.Mat();
  const blurred = new cv.Mat();
  const thresh = new cv.Mat();
  const contours = new cv.MatVector();
  const hierarchy = new cv.Mat();

  try {
    cv.cvtColor(image, gray, cv.COLOR_RGBA2GRAY);

    const { minVal, maxVal } = cv.minMaxLoc(gray);
    if (maxVal - minVal < MIN_CONTRAST_RANGE) return null;

    cv.GaussianBlur(gray, blurred, new cv.Size(5, 5), 0);
    cv.threshold(blurred, thresh, 0, 255, cv.THRESH_BINARY + cv.THRESH_OTSU);
    cv.findContours(thresh, contours, hierarchy, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE);

    let largestIdx = -1;
    let largestArea = 0;
    for (let i = 0; i < contours.size(); i++) {
      const contour = contours.get(i);
      const area = cv.contourArea(contour);
      if (area > largestArea) {
        largestArea = area;
        largestIdx = i;
      }
      contour.delete();
    }

    const minArea = MIN_SHEET_AREA_FRACTION * image.rows * image.cols;
    if (largestIdx < 0 || largestArea < minArea) return null;

    const largest = contours.get(largestIdx);
    try {
      const peri = cv.arcLength(largest, true);
      const approx = new cv.Mat();
      let points: Point[] | null = null;
      let method: DetectedSheetBoundary['method'] = 'polygon';
      try {
        cv.approxPolyDP(largest, approx, APPROX_EPSILON_RATIO * peri, true);
        if (approx.rows === 4) {
          points = matToPoints(approx);
        }
      } finally {
        approx.delete();
      }

      if (!points) {
        const rect = cv.minAreaRect(largest);
        points = rotatedRectToPoints(rect);
        method = 'bounding-rectangle';
      }

      return { corners: orderQuadrilateralCorners(points), method };
    } finally {
      largest.delete();
    }
  } finally {
    gray.delete();
    blurred.delete();
    thresh.delete();
    contours.delete();
    hierarchy.delete();
  }
}
